package com.openminis.app.ui.chat

// [T-android-split-chat] Flat-chat-item data model + flatten/merge transforms
// extracted verbatim from ChatScreen.kt: FlatChatItem (sealed), mergeStreamingOverlay,
// buildFlatChatItems. Imports trimmed after ChatScreen.kt split; all internal.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.filled.Build
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.input.key.key
import androidx.compose.ui.unit.dp
import com.mikepenz.markdown.m3.Markdown
import com.openminis.app.data.model.ThinkingLevel

internal sealed class FlatChatItem {
    abstract val key: String
    abstract val contentType: String

    /**
     * Defensive-dedupe helper: the same row with `#<n>` appended to the key.
     * The suffix lives ONLY in the key — message ids and `messageId` fields
     * stay clean so key parsing (FlatKeys.parse) always recovers the real
     * id. Before this hook the dedupe rewrote UserBubble.message.id itself,
     * which is what desynced the up-button target resolution.
     */
    abstract fun withKeySuffix(suffix: String): FlatChatItem

    /**
     * Cheap-equals — see [AssistantText]. User messages are short and don't
     * stream, but during a streaming overlay rebuild we still re-create the
     * entire FlatChatItem list, and LazyColumn calls equals to decide skip.
     * Compare by id + reference identity of the wrapped ChatMessage.
     */
    /**
     * [T-android-candidate-bubble-gap] `precededByUser` is true when the
     * immediately-preceding flat item is also a user bubble (e.g. two
     * candidate / queued messages sent back to back). Consecutive user
     * bubbles have no intervening AssistantHeader row to create visual
     * separation, and the LazyColumn's `spacedBy(2.dp)` alone is too tight
     * — the two bubbles read as one. When set, UserMessageBubble adds extra
     * top padding so the pair is clearly two distinct messages.
     */
    class UserBubble(
        val message: ChatMessage,
        val precededByUser: Boolean = false,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_USER, message.id) + keySuffix
        override val contentType = "user"
        override fun withKeySuffix(suffix: String): FlatChatItem = UserBubble(message, precededByUser, suffix)
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is UserBubble) return false
            // ChatMessage is a data class; reuse its equals (cheap for user
            // bubbles which carry short content and small attachment lists).
            return message == other.message && precededByUser == other.precededByUser
        }
        override fun hashCode(): Int = message.hashCode() * 31 + precededByUser.hashCode()
    }

    data class AssistantHeader(
        val messageId: String,
        val speakerName: String = "",
        val speakerVendor: String = "",
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_HEADER, messageId) + keySuffix
        override val contentType = "header"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    /**
     * Equality on this class previously compared every field including
     * `messageMarkdown` — a CONCATENATED markdown of the entire parent
     * assistant message — char-by-char. During streaming, LazyColumn called
     * the autogenerated equals to decide stable-skip per item, and a typical
     * 50-fragment message with 1 KB per fragment ate ~3.7 seconds of main
     * thread (profile #3, `String.charAt` at 91.8% exclusive). The hand-
     * rolled equals below compares cheap stable identity (key fields + the
     * String *reference* of large bodies) instead, falling back to length
     * if the references differ — never a full char-by-char walk.
     */
    class AssistantText(
        val messageId: String,
        val block: AssistantBlock,
        val isStreaming: Boolean,
        /** Joined raw markdown of the parent message, used by the selection toolbar's Copy Markdown action. */
        val messageMarkdown: String,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_TEXT, messageId, block.id) + keySuffix
        override val contentType = "text"
        override fun withKeySuffix(suffix: String): FlatChatItem =
            AssistantText(messageId, block, isStreaming, messageMarkdown, suffix)
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantText) return false
            return messageId == other.messageId &&
                block === other.block &&
                isStreaming == other.isStreaming &&
                messageMarkdown.length == other.messageMarkdown.length
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + System.identityHashCode(block)
            h = h * 31 + isStreaming.hashCode()
            h = h * 31 + messageMarkdown.length
            return h
        }
    }

    /**
     * One rendered markdown sub-block (paragraph, code block, list, …) of an
     * AssistantText. Pattern A from the streaming-markdown research: each
     * block is its own LazyColumn item so completed blocks are frozen by
     * LazyList's per-item anchor and only the trailing "live" block
     * re-parses on every chunk. Replaces the previous "whole AssistantText
     * is a single LazyColumn item containing an internal Column of blocks"
     * design which caused the user's scroll position to drift mid-stream.
     */
    /**
     * See [AssistantText] for the rationale behind the hand-rolled equals.
     * `rawText` and `messageMarkdown` are both potentially long; we compare
     * by length (cheap proxy for "has content grown") and identity instead
     * of char-by-char.
     */
    class AssistantMarkdownBlock(
        val messageId: String,
        val parentBlockId: String,
        val rawText: String,
        val blockIndex: Int,
        val isLastBlockOfMessage: Boolean,
        val messageIsStreaming: Boolean,
        /** Joined raw markdown of the parent message, used by Copy Markdown. */
        val messageMarkdown: String,
        val showTranslate: Boolean = false,
        val segmentText: String = "",
        val translateWholeReply: Boolean = false,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_MDBLOCK, messageId, parentBlockId, blockIndex) + keySuffix
        override val contentType = "mdblock"
        override fun withKeySuffix(suffix: String): FlatChatItem = AssistantMarkdownBlock(
            messageId = messageId,
            parentBlockId = parentBlockId,
            rawText = rawText,
            blockIndex = blockIndex,
            isLastBlockOfMessage = isLastBlockOfMessage,
            messageIsStreaming = messageIsStreaming,
            messageMarkdown = messageMarkdown,
            showTranslate = showTranslate,
            segmentText = segmentText,
            translateWholeReply = translateWholeReply,
            keySuffix = suffix,
        )
        /** True when this fragment is the streaming tail of a live message. */
        val isStreaming: Boolean get() = messageIsStreaming && isLastBlockOfMessage
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantMarkdownBlock) return false
            return messageId == other.messageId &&
                parentBlockId == other.parentBlockId &&
                blockIndex == other.blockIndex &&
                isLastBlockOfMessage == other.isLastBlockOfMessage &&
                messageIsStreaming == other.messageIsStreaming &&
                rawText.length == other.rawText.length &&
                messageMarkdown.length == other.messageMarkdown.length &&
                showTranslate == other.showTranslate &&
                segmentText.length == other.segmentText.length &&
                translateWholeReply == other.translateWholeReply
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + parentBlockId.hashCode()
            h = h * 31 + blockIndex
            h = h * 31 + isLastBlockOfMessage.hashCode()
            h = h * 31 + messageIsStreaming.hashCode()
            h = h * 31 + rawText.length
            h = h * 31 + messageMarkdown.length
            h = h * 31 + if (showTranslate) 1 else 0
            h = h * 31 + segmentText.length
            h = h * 31 + if (translateWholeReply) 1 else 0
            return h
        }
    }

    data class AssistantThinking(
        val messageId: String,
        val block: AssistantBlock,
        val isLast: Boolean,
        val messageIsStreaming: Boolean,
        // T300: thinking level captured at the message's creation. Null
        // for assistant messages restored from DB (legacy / pre-T300) —
        // the renderer falls back to the chat's current level.
        val messageThinkingLevel: com.openminis.app.data.model.ThinkingLevel? = null,
        // [T-android-thinking-auto-collapse] True when this thinking block
        // is the LAST block of any kind in the message (including text /
        // tool_use), not merely the last thinking block. Drives the
        // auto-collapse `isStreaming` signal so a thinking block flips to
        // collapsed the moment a subsequent text or tool block arrives —
        // mirrors iOS ThinkingBlockView, which only sees `isStreaming=true`
        // while it really is the trailing block. Defaults false so DB-
        // restored / legacy items render collapsed (the pre-change
        // behaviour for non-trailing thinking).
        val isLastBlockOverall: Boolean = false,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_THINKING, messageId, block.id) + keySuffix
        override val contentType = "thinking"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    /**
     * [T-process-run-card] Unified "work process" card — ONE collapsible
     * surface that owns the whole process of an assistant turn while
     * folding is ON: a live phase header (spinner + "正在思考中…"),
     * entries appended chronologically as the agent works (tool rows with
     * a 查看 button, thinking rows, the turn error), and a collapsed bar
     * ("工作过程 · 已调用 N 个工具 · 47s").
     *
     * Replaces the old AssistantProcessSummary fold bar + the in-list live
     * thinking row + the in-flight tool pills: those three surfaces fought
     * for attention and the user saw "everything piled together, no sense
     * of what is running". The card is emitted directly after the
     * AssistantHeader row, so under reverseLayout + asReversed it renders
     * at the visual TOP of the turn — the running state reads as the
     * turn's header and the reply text streams in below it.
     *
     * Auto-expand: while the turn is live AND no reply text has arrived
     * the card is expanded (live process view). The moment reply text
     * starts streaming the card auto-collapses — "一段运行完成后输出内容
     * 时折叠中间的过程" — and finished turns stay collapsed. Manual taps
     * override via expandedProcessIds / collapsedProcessIds.
     *
     * [blocks] is compared by REFERENCE in equals: AssistantBlock is a
     * data class whose equals walks full content strings, and the flat
     * rebuild fires per streaming tick — a content-based equals would
     * re-compare kilobytes of tool output on every token.
     */
    class ProcessRunCard(
        val messageId: String,
        val blocks: List<AssistantBlock>,
        val isRunning: Boolean,
        val phaseKind: ProcessPhaseKind,
        val phaseToolName: String,
        val expanded: Boolean,
        val hasFailure: Boolean,
        /** Summed block durations for the collapsed "· 47s" suffix. 0 when
         *  no block recorded a duration — the bar then omits the suffix. */
        val totalMs: Long,
        /** One-line task description from the preceding user message. */
        val taskDescription: String = "",
        /** Turn-level error (message.error) rendered as a red row inside
         *  the card while the card is showing. */
        val errorText: String = "",
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_PROCESS, messageId) + keySuffix
        override val contentType = "process"
        override fun withKeySuffix(suffix: String): FlatChatItem = ProcessRunCard(
            messageId, blocks, isRunning, phaseKind, phaseToolName, expanded,
            hasFailure, totalMs, taskDescription, errorText, suffix,
        )
        override fun equals(other: Any?): Boolean = this === other
        override fun hashCode(): Int = messageId.hashCode()
    }

    data class AssistantToolUse(
        val messageId: String,
        val block: AssistantBlock,
        val allToolBlocks: List<AssistantBlock>,
        /** True if this is the last cancelled tool in its message — only one Retry button per message. */
        val isLastCancelled: Boolean = false,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_TOOL, messageId, block.id) + keySuffix
        override val contentType = "tool"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    data class AssistantInfo(
        val messageId: String,
        val block: AssistantBlock,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_INFO, messageId, block.id) + keySuffix
        override val contentType = "info"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    data class AssistantTyping(val messageId: String, private val keySuffix: String = "") : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_TYPING, messageId) + keySuffix
        override val contentType = "typing"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    data class AssistantError(
        val messageId: String,
        val error: String,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_ERROR, messageId) + keySuffix
        override val contentType = "error"
        override fun withKeySuffix(suffix: String): FlatChatItem = copy(keySuffix = suffix)
    }

    /**
     * See [AssistantText] — same cheap-equals rationale.
     */
    class AssistantLegacyContent(
        val messageId: String,
        val content: String,
        val isStreaming: Boolean,
        /** Same as content here (no separate text-block markdown for legacy rows). */
        val messageMarkdown: String = content,
        private val keySuffix: String = "",
    ) : FlatChatItem() {
        override val key = FlatKeys.of(FlatKeys.KIND_LEGACY, messageId) + keySuffix
        override val contentType = "legacy"
        override fun withKeySuffix(suffix: String): FlatChatItem =
            AssistantLegacyContent(messageId, content, isStreaming, messageMarkdown, suffix)
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantLegacyContent) return false
            return messageId == other.messageId &&
                isStreaming == other.isStreaming &&
                content.length == other.content.length &&
                messageMarkdown.length == other.messageMarkdown.length
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + isStreaming.hashCode()
            h = h * 31 + content.length
            h = h * 31 + messageMarkdown.length
            return h
        }
    }
}

/**
 * T-streaming-side-channel: overlay any active [StreamingDelta]s on top of
 * the canonical [messages] list, producing the snapshot
 * [buildFlatChatItems] should fold over. The original [messages] list is
 * never mutated; affected entries are replaced via `copy()` so downstream
 * keying / equality stays correct. When [streaming] is empty the input is
 * returned as-is to skip the per-element walk on idle frames.
 */
internal fun mergeStreamingOverlay(
    messages: List<ChatMessage>,
    streaming: Map<String, StreamingDelta>,
): List<ChatMessage> {
    if (streaming.isEmpty()) return messages
    return messages.map { m ->
        val delta = streaming[m.id] ?: return@map m
        // [T-android-stream-duplicate-text] `delta.content` is the WHOLE
        // assistant reply accumulated across every tool round, while
        // `delta.toolBlocks` is that same reply split chronologically into
        // per-round text/tool blocks (the producer appends each round's text
        // block and keeps advancing only that block; rounds never repeat
        // earlier text). Overwriting one block with the cumulative string
        // therefore duplicated everything before it: whichever text block was
        // last kept its own fragment AND re-rendered rounds 1..N-1 again, so a
        // turn with text A → tool → text B painted "A" then "A+B".
        //
        // The blocks are the authority for what each row renders, so take them
        // verbatim:
        //  - delta.toolBlocks non-empty → newest per-round snapshot. copy() it
        //    (the delta list is shared) but never rewrite a block's content.
        //  - delta.toolBlocks empty but the canonical message already carries
        //    blocks → keep those. Rewriting the last text block with the
        //    cumulative content would re-introduce the exact duplication.
        //  - canonical blocks also empty (pre-first-block turn) → stay empty;
        //    the typing indicator renders and the legacy fallback below is
        //    driven by content == "" while nothing has arrived.
        // Fall back to m.toolBlocks rather than [] so a machine-migration
        // streaming message without a toolBlocks list keeps its blocks.
        val blocks = when {
            delta.toolBlocks.isNotEmpty() -> delta.toolBlocks
            m.toolBlocks.isNotEmpty() -> m.toolBlocks
            else -> emptyList()
        }
        m.copy(
            // Content stays authoritative on its own field (non-render
            // consumers: persistence, copy/translate fallbacks).
            content = delta.content,
            isStreaming = true,
            toolBlocks = blocks,
            isAwaitingModelResponse = delta.isAwaitingModelResponse,
        )
    }
}

internal fun buildFlatChatItems(
    messages: List<ChatMessage>,
    // [T-android-perf-logging] Optional — when supplied, emit a progress
    // breadcrumb every 100 messages so a low-memory repro shows which batch
    // drives the heap up. Null (default) skips all progress logging, so the
    // hot per-token streaming rebuild path stays log-free.
    sessionId: String? = null,
    // [T-android-stream-pipeline-incremental] Build rows only for
    // messages[fromIndex, size). Neighbor lookbacks (precededByUser /
    // isResumeContinuation) still read the FULL list, so a suffix built with
    // fromIndex > 0 is row-for-row identical to the same span of a full
    // build — rows never depend on later messages, only earlier ones.
    fromIndex: Int = 0,
    // Dedupe continuity for split builds: pass the key set of the frozen
    // prefix so the defensive key-collision suffixing behaves exactly as a
    // single full build would.
    seedKeys: Set<String> = emptySet(),
    showCompletedToolCards: Boolean = true,
    foldAiProcess: Boolean = false,
    expandedProcessIds: Set<String> = emptySet(),
    // [T-process-run-card] Manual-collapse overrides: a turn the user
    // explicitly folded while it was live (auto-expanded). Auto state
    // applies when the id is in neither set — see
    // [effectiveProcessExpanded].
    collapsedProcessIds: Set<String> = emptySet(),
    activeSubAgentToolIds: Set<String> = emptySet(),
): List<FlatChatItem> {
    val out = mutableListOf<FlatChatItem>()
    val usedKeys = if (seedKeys.isEmpty()) mutableSetOf() else seedKeys.toMutableSet()
    fun dedupe(item: FlatChatItem): FlatChatItem {
        // Defensive: duplicated keys crash LazyColumn. If any slip through, suffix
        // a counter until unique. This should never fire if upstream dedup is
        // correct. The suffix is appended to the KEY only — never to
        // message.id / messageId (that used to desync every key consumer; see
        // FlatKeys KDoc).
        if (usedKeys.add(item.key)) return item
        var n = 2
        while (!usedKeys.add(item.key + "#$n")) n++
        return item.withKeySuffix("#$n")
    }
    for (idx in fromIndex until messages.size) {
        val rawMessage = messages[idx]
        // Finished group utterances drop their tool cards. A live speaker still
        // shows the current thinking block or tool card.
        val hideSpeakerTools = !rawMessage.speakerName.isNullOrBlank() &&
            !rawMessage.isStreaming && !rawMessage.isAwaitingModelResponse
        // A sub-agent transcript card is hidden only while its run is still
        // live in the top bar — the bar and the card would otherwise show the
        // same run twice. Once the run finishes the bar drops it, so the card
        // must come back here: with the old "hide whenever the bar is on"
        // rule a completed sub-agent left no trace anywhere on the session
        // page and the user could not tell it had finished at all.
        fun hiddenSubAgent(block: AssistantBlock): Boolean =
            activeSubAgentToolIds.isNotEmpty() &&
                isSubAgentTranscriptCard(block) &&
                (block.id in activeSubAgentToolIds ||
                    block.id.substringBefore("#sub-") in activeSubAgentToolIds)
        val message = if (
            rawMessage.toolBlocks.none(::hiddenSubAgent) &&
            !hideSpeakerTools
        ) {
            rawMessage
        } else {
            rawMessage.copy(toolBlocks = rawMessage.toolBlocks.filterNot { block ->
                hiddenSubAgent(block) ||
                    (hideSpeakerTools && block.kind == "tool_use")
            })
        }
        // [T-android-perf-logging] Per-100-message progress breadcrumb.
        // `out.size` is the running row count, so a sudden jump between two
        // progress lines localizes the heavy batch. Only fires on the
        // full-build path (sessionId != null), never per streaming token.
        if (sessionId != null && idx > 0 && idx % 100 == 0) {
            com.openminis.app.diagnostics.PerfLongCtx.step(
                sessionId,
                "buildFlatChatItems.progress",
                "msgIdx=$idx of=${messages.size} rowsSoFar=${out.size}",
            )
        }
        if (message.role == "user") {
            // [T-android-candidate-bubble-gap] Flag when the previous message
            // is also a user message so the bubble can add a separating top
            // gap — back-to-back candidate / queued sends otherwise have no
            // AssistantHeader between them and visually merge.
            val prevIsUser = idx > 0 && messages[idx - 1].role == "user"
            out.add(dedupe(FlatChatItem.UserBubble(message, precededByUser = prevIsUser)))
            continue
        }
        // System messages (slash-command notices, compact divider, etc.) render
        // as horizontal-divider rows — no "Minis Ultra" attribution, no card. Skip
        // the assistant header so each info block stands on its own. Mirrors
        // iOS systemDividerRow / compactDividerRow.
        val isSystem = message.role == "system"
        val joinedMarkdown = run {
            val parts = message.toolBlocks
                .filter { it.kind == "text" && it.content.isNotEmpty() }
                .joinToString("\n\n") { it.content }
            if (parts.isNotEmpty()) parts else message.content
        }
        // T83: when Resume creates a fresh assistant bubble after the user
        // stopped a streaming turn, the previous (cancelled) assistant
        // message is right before this one in the list. Visually they should
        // read as one continuous turn — suppress the duplicate "Minis Ultra"
        // header. Skip system rows when looking back since they render as
        // dividers, not as separate speaker turns. iOS achieves this by
        // reusing the existing ChatMessage in runAgentLoop(resumingAt:);
        // we reach the same end-result at the render layer.
        val prevNonSystem = (idx - 1 downTo 0).asSequence()
            .map { messages[it] }
            .firstOrNull { it.role != "system" }
        // Resume reuses the previous assistant turn, so a second unnamed bubble
        // must not grow a second soul header. A different group-chat speaker
        // is a new person and always gets their own mark. Same name means the
        // same model continued, not a new participant.
        val prevSpeaker = prevNonSystem?.speakerName?.trim().orEmpty()
        val thisSpeaker = message.speakerName?.trim().orEmpty()
        val isResumeContinuation = prevNonSystem?.role == "assistant" &&
            prevSpeaker == thisSpeaker

        val blocks = message.toolBlocks
        val toolPillBlocks = blocks.filter { it.kind == "tool_use" }
        val lastThinkingId = blocks.lastOrNull { it.kind == "thinking" }?.id
        // [T-android-thinking-auto-collapse] Id of the last block of ANY
        // kind — used to flip the trailing thinking block's auto-collapse
        // signal the moment a subsequent text / tool_use arrives. See
        // AssistantThinking.isLastBlockOverall KDoc.
        val lastBlockId = blocks.lastOrNull()?.id
        val lastTextIdx = blocks.indexOfLast { it.kind == "text" }
        val hasAnyTextBlock = lastTextIdx >= 0
        // Only the last cancelled tool_use in the message gets the Retry button —
        // retryLast() re-runs the whole turn, so one button is enough.
        val lastCancelledToolId = blocks.lastOrNull { it.kind == "tool_use" && it.toolStatus == ToolBlockStatus.CANCELLED }?.id
        // [T-process-run-card] The unified process card replaces the old
        // fold-bar + live-thinking-row + in-flight-tool-pill trio. While
        // folding is ON the card owns EVERY thinking/tool block of the
        // turn: live phase header (spinner + "正在思考中…"), entries
        // appended chronologically as the agent works, and a collapsed
        // bar ("工作过程 · 已调用 N 个工具 · 47s") once reply text streams.
        val isTurnRunning = message.isStreaming || message.isAwaitingModelResponse
        val turnHasReplyText = hasReplyText(message)
        val processExpanded = effectiveProcessExpanded(
            messageId = message.id,
            isRunning = isTurnRunning,
            hasReplyText = turnHasReplyText,
            expandedIds = expandedProcessIds,
            collapsedIds = collapsedProcessIds,
        )
        val processCardBlocks = if (foldAiProcess && !isSystem) {
            blocks.filter { block ->
                block.kind == "thinking" ||
                    (block.kind == "tool_use" && !isAlwaysVisibleProcessTool(block))
            }
        } else {
            emptyList()
        }
        val showProcessCard = processCardBlocks.isNotEmpty()
        // The translate logic keeps the old predicate family (fold on +
        // process present ⇒ whole-reply translation of the last text
        // block); for finished turns this equals the old
        // hasFoldableProcess, and live turns never translate.
        val showProcessSummary = showProcessCard
        val replyText = AssistantReplyText.joined(blocks)
        // [T-process-run-card] One-line task description from the preceding
        // user message — the expanded card shows it so a scrolled-back
        // process card still says WHAT this run was about.
        val taskDescription = if (idx > 0) {
            val prev = messages[idx - 1]
            if (prev.role == "user") {
                prev.content.lineSequence()
                    .firstOrNull { it.isNotBlank() }?.trim()?.take(64).orEmpty()
            } else ""
        } else ""
        if (!isSystem && !isResumeContinuation) {
            // [T-android-fold-toolonly-blank] A turn whose entire visible
            // payload is the process card (no text/info/error/interactive
            // tool) hides the header row: header padding + spacedBy above
            // an otherwise card-only turn read as a blank band in the
            // reverse-layout list. The card alone carries the turn.
            val headerVisibleInBlocks = blocks.any { block ->
                when (block.kind) {
                    "text" -> block.content.isNotEmpty()
                    "info" -> true
                    "tool_use" -> isAlwaysVisibleProcessTool(block)
                    else -> false
                }
            }
            val headerHiddenByFold = showProcessCard && !headerVisibleInBlocks &&
                message.content.isBlank() && message.error == null
            if (!headerHiddenByFold) {
                out.add(dedupe(FlatChatItem.AssistantHeader(
                    message.id,
                    message.speakerName.orEmpty(),
                    message.speakerVendor.orEmpty(),
                )))
            }
        }
        // [T-process-run-card] Emitted directly after the header so under
        // reverseLayout + asReversed it renders at the visual TOP of the
        // turn — the running state reads as the turn's header and the
        // reply text streams in below it (the old summary bar sat below
        // the reply, where a running turn showed nothing at the top).
        if (showProcessCard) {
            out.add(dedupe(FlatChatItem.ProcessRunCard(
                messageId = message.id,
                blocks = processCardBlocks,
                isRunning = isTurnRunning,
                phaseKind = processPhaseKind(message),
                phaseToolName = processPhaseToolName(message),
                expanded = processExpanded,
                hasFailure = processCardBlocks.any { block ->
                    block.kind == "tool_use" && (
                        block.toolStatus == ToolBlockStatus.FAILED ||
                            block.toolStatus == ToolBlockStatus.TIMEOUT
                        )
                },
                totalMs = blocks.sumOf { it.durationMs },
                taskDescription = taskDescription,
                errorText = message.error.orEmpty(),
            )))
        }
        blocks.forEachIndexed { index, block ->
            when (block.kind) {
                "text" -> {
                    if (block.content.isNotEmpty()) {
                        val isLastText = index == lastTextIdx
                        // Pattern A: split this text block's content into
                        // independent markdown fragments so each becomes its
                        // own LazyColumn item. Frozen prefix fragments are
                        // anchored separately by LazyList; only the trailing
                        // live fragment can change height during streaming.
                        //
                        // [T-android-defensive-fragment-merge] For a FROZEN
                        // (non-streaming) message, coalesce adjacent
                        // plain-text fragments so a long reply produces a
                        // handful of rows instead of dozens — cuts cold-open
                        // full-build row count ~8x and eases GC pressure on
                        // low-memory devices. The live streaming tail message
                        // keeps fine-grained fragments so only the trailing
                        // paragraph re-parses per token (Pattern A jank
                        // optimization preserved). Code fences stay standalone
                        // either way.
                        val rawFragments = splitMarkdownIntoBlockTexts(block.content)
                        // [T-android-stream-end-reflow-flicker-v18] Preserve
                        // per-fragment FlatChatItem keys across the
                        // streaming→idle boundary. Previously the trailing
                        // text block kept rawFragments only while
                        // `message.isStreaming==true`; the moment it flipped
                        // false the fragments coalesced into fewer rows, all
                        // mdblock:msgId:parentBlockId:N keys for N >= K
                        // suddenly vanished from the flatItems list. That
                        // wipe-and-rebuild was the "整个页面像被重刷" the
                        // user reported — LazyColumn lost every key it was
                        // using to anchor the viewport, fell back to numeric
                        // firstVisibleItemIndex, and parked the viewport on
                        // whatever row happened to take that numeric slot
                        // (often the previous assistant message).
                        //
                        // Fix: keep the live (== last in the list) text block
                        // on rawFragments regardless of isStreaming. The
                        // boundary that actually warrants coalesce is "a
                        // NEWER message exists below this one" — i.e. a
                        // subsequent user turn pushed this assistant turn
                        // into history. Until then, the same key set the
                        // user was scrolled into stays valid.
                        // [T-android-flatitems-sublist-cme] Index-based scan
                        // instead of messages.subList(idx+1, size).all{} — a
                        // subList is a live view sharing the parent's modCount,
                        // which threw ConcurrentModificationException when the
                        // backing list changed under it. A plain index loop
                        // touches no view.
                        val isLastAssistantTurn = idx == messages.lastIndex ||
                            (idx + 1 until messages.size).all { messages[it].role != "assistant" }
                        val fragments = if (isLastText && isLastAssistantTurn) {
                            rawFragments
                        } else {
                            coalesceMarkdownFragments(rawFragments)
                        }
                        if (fragments.isEmpty()) {
                            // Defensive: if the splitter returns nothing for
                            // a non-empty input (shouldn't happen), fall back
                            // to a single fragment so content isn't dropped.
                            out.add(dedupe(FlatChatItem.AssistantMarkdownBlock(
                                messageId = message.id,
                                parentBlockId = block.id,
                                rawText = block.content,
                                blockIndex = 0,
                                isLastBlockOfMessage = isLastText && message.isStreaming,
                                messageIsStreaming = message.isStreaming && isLastText,
                                messageMarkdown = joinedMarkdown,
                                showTranslate = !message.isStreaming && block.content.isNotBlank() &&
                                    (!showProcessSummary || isLastText),
                                segmentText = if (showProcessSummary && isLastText) replyText else block.content,
                                translateWholeReply = showProcessSummary && isLastText &&
                                    !message.isStreaming && block.content.isNotBlank(),
                            )))
                        } else {
                            fragments.forEachIndexed { fragIdx, raw ->
                                val isLastFragOfText = fragIdx == fragments.lastIndex
                                out.add(dedupe(FlatChatItem.AssistantMarkdownBlock(
                                    messageId = message.id,
                                    parentBlockId = block.id,
                                    rawText = raw,
                                    blockIndex = fragIdx,
                                    isLastBlockOfMessage = isLastText && isLastFragOfText,
                                    messageIsStreaming = message.isStreaming && isLastText,
                                    messageMarkdown = joinedMarkdown,
                                    showTranslate = isLastFragOfText && !message.isStreaming && block.content.isNotBlank() &&
                                        (!showProcessSummary || isLastText),
                                    segmentText = if (showProcessSummary && isLastText && isLastFragOfText) replyText
                                        else if (isLastFragOfText) block.content else "",
                                    translateWholeReply = showProcessSummary && isLastText && isLastFragOfText &&
                                        !message.isStreaming && block.content.isNotBlank(),
                                )))
                            }
                        }
                    }
                }
                "thinking" -> {
                    // [T-process-run-card] While the card is showing it owns
                    // every thinking block (the live one included — the
                    // card's live entry ticks "思考中 (2.6s)"); the
                    // standalone row only renders when folding is OFF.
                    if (!showProcessCard) {
                        out.add(dedupe(FlatChatItem.AssistantThinking(
                            messageId = message.id,
                            block = block,
                            isLast = block.id == lastThinkingId,
                            messageIsStreaming = message.isStreaming,
                            messageThinkingLevel = message.thinkingLevel,
                            isLastBlockOverall = block.id == lastBlockId,
                        )))
                    }
                }
                "info" -> out.add(dedupe(FlatChatItem.AssistantInfo(
                    messageId = message.id,
                    block = block,
                )))
                else -> {
                    // [T-process-run-card] With the card showing, tool pills
                    // are suppressed except ask_user_question (an
                    // interactive prompt, not process history — it must
                    // stay reachable outside the card).
                    val emitToolRow = if (showProcessCard) {
                        isAlwaysVisibleProcessTool(block)
                    } else {
                        shouldShowToolUseRow(block, showCompletedToolCards)
                    }
                    if (emitToolRow) {
                        out.add(dedupe(FlatChatItem.AssistantToolUse(
                            messageId = message.id,
                            block = block,
                            allToolBlocks = toolPillBlocks,
                            isLastCancelled = block.id == lastCancelledToolId,
                        )))
                    }
                }
            }
        }

        // [T-process-run-card] The old fold bar was emitted here (after the
        // content blocks, visually below the reply). The unified card now
        // renders at the visual TOP of the turn — see the emission right
        // after the AssistantHeader above.

        // Typing indicator: show while streaming and either (a) no visible
        // content has arrived yet, or (b) we're in the network gap waiting
        // on the model's next response (e.g. after tool results were sent
        // back). Mirrors iOS: `isActiveMessage && (!hasVisibleContent || isAwaitingModelResponse)`.
        //
        // [T-android-typing-hidden-thinking] "Visible" must mean WILL RENDER,
        // not merely "exists". Two blocks used to count as content while
        // drawing nothing, killing the indicator into a blank gap ("thinking
        // 还没等到内容出现就消失了"):
        //  - a "thinking" block when the message's thinking level is OFF —
        //    forced-reasoning models (MiniMax M2, Grok…) still stream
        //    reasoning_content, but ChatScreen suppresses the row when the
        //    snapshot level is disabled (T300), so the user saw nothing;
        //  - a freshly-created "text" block whose content is still empty.
        // A null thinkingLevel snapshot falls back to the chat's CURRENT
        // level in the renderer, which this pure builder can't read — treat
        // it as visible (legacy messages; conservative, old behavior).
        val hasVisibleContent = message.content.isNotEmpty() || blocks.any {
            when (it.kind) {
                "info" -> false
                // [T-android-thinking-forced-visible] A thinking block with
                // content renders (forced-reasoning models stream reasoning
                // even when the request level is OFF), so it counts as
                // visible content for the typing indicator. Empty block =
                // still waiting, same as before.
                "thinking" -> it.content.isNotBlank()
                "text" -> it.content.isNotEmpty()
                else -> true // tool_use pills render immediately
            }
        }
        if (message.isStreaming && !showProcessCard &&
            (!hasVisibleContent || message.isAwaitingModelResponse)
        ) {
            out.add(dedupe(FlatChatItem.AssistantTyping(message.id)))
        }

        // Legacy fallback: pre-migration sessions stored all text in message.content
        // with no text-kind blocks. Render it after blocks in that case only.
        if (!hasAnyTextBlock && message.content.isNotEmpty()) {
            out.add(dedupe(FlatChatItem.AssistantLegacyContent(
                messageId = message.id,
                content = message.content,
                isStreaming = message.isStreaming,
            )))
        }

        // Inline error banner. [T-process-run-card] While the card is
        // showing the turn error rides INSIDE it (red row under the
        // entries) so the failure reads as part of the process.
        if (!showProcessCard) message.error?.let {
            out.add(dedupe(FlatChatItem.AssistantError(message.id, it)))
        }
    }
    return out
}

internal fun shouldShowToolUseRow(block: AssistantBlock, showCompletedToolCards: Boolean): Boolean {
    if (showCompletedToolCards) return true
    return when (block.toolStatus) {
        ToolBlockStatus.SUCCESS, ToolBlockStatus.FAILED, ToolBlockStatus.TIMEOUT -> false
        else -> true
    }
}

private val SUB_AGENT_TRANSCRIPT_TOOLS = setOf("spawn_agent", "run_subagent", "dispatch_agents")

/** Chat cards that duplicate the sub-agent chip. Hidden while chip mode is on. */
internal fun isSubAgentTranscriptCard(block: AssistantBlock): Boolean =
    block.kind == "tool_use" && (
        block.toolName in SUB_AGENT_TRANSCRIPT_TOOLS || "#sub-" in block.id
    )
