package com.openminis.app.ui.chat

// [T-android-split-chat] Flat-chat-item data model + flatten/merge transforms
// extracted verbatim from ChatScreen.kt: FlatChatItem (sealed), mergeStreamingOverlay,
// buildFlatChatItems. Imports trimmed after ChatScreen.kt split; all internal.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.filled.Build
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.input.key.key
import androidx.compose.ui.unit.dp
import com.mikepenz.markdown.m3.Markdown
import com.openminis.app.data.model.ThinkingLevel

internal sealed class FlatChatItem {
    abstract val key: String
    abstract val contentType: String

    /**
     * Cheap-equals — see [AssistantText]. User messages are short and don't
     * stream, but during a streaming overlay rebuild we still re-create the
     * entire FlatChatItem list, and LazyColumn calls equals to decide skip.
     * Compare by id + reference identity of the wrapped ChatMessage.
     */
    /**
     * [T-android-candidate-bubble-gap] `precededByUser` is true when the
     * immediately-preceding flat item is also a user bubble (e.g. two
     * candidate / queued messages sent back to back). Consecutive user
     * bubbles have no intervening AssistantHeader row to create visual
     * separation, and the LazyColumn's `spacedBy(2.dp)` alone is too tight
     * — the two bubbles read as one. When set, UserMessageBubble adds extra
     * top padding so the pair is clearly two distinct messages.
     */
    class UserBubble(
        val message: ChatMessage,
        val precededByUser: Boolean = false,
    ) : FlatChatItem() {
        override val key = "user:${message.id}"
        override val contentType = "user"
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is UserBubble) return false
            // ChatMessage is a data class; reuse its equals (cheap for user
            // bubbles which carry short content and small attachment lists).
            return message == other.message && precededByUser == other.precededByUser
        }
        override fun hashCode(): Int = message.hashCode() * 31 + precededByUser.hashCode()
    }

    data class AssistantHeader(val messageId: String) : FlatChatItem() {
        override val key = "header:$messageId"
        override val contentType = "header"
    }

    /**
     * Equality on this class previously compared every field including
     * `messageMarkdown` — a CONCATENATED markdown of the entire parent
     * assistant message — char-by-char. During streaming, LazyColumn called
     * the autogenerated equals to decide stable-skip per item, and a typical
     * 50-fragment message with 1 KB per fragment ate ~3.7 seconds of main
     * thread (profile #3, `String.charAt` at 91.8% exclusive). The hand-
     * rolled equals below compares cheap stable identity (key fields + the
     * String *reference* of large bodies) instead, falling back to length
     * if the references differ — never a full char-by-char walk.
     */
    class AssistantText(
        val messageId: String,
        val block: AssistantBlock,
        val isStreaming: Boolean,
        /** Joined raw markdown of the parent message, used by the selection toolbar's Copy Markdown action. */
        val messageMarkdown: String,
    ) : FlatChatItem() {
        override val key = "text:$messageId:${block.id}"
        override val contentType = "text"
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantText) return false
            return messageId == other.messageId &&
                block === other.block &&
                isStreaming == other.isStreaming &&
                messageMarkdown.length == other.messageMarkdown.length
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + System.identityHashCode(block)
            h = h * 31 + isStreaming.hashCode()
            h = h * 31 + messageMarkdown.length
            return h
        }
    }

    /**
     * One rendered markdown sub-block (paragraph, code block, list, …) of an
     * AssistantText. Pattern A from the streaming-markdown research: each
     * block is its own LazyColumn item so completed blocks are frozen by
     * LazyList's per-item anchor and only the trailing "live" block
     * re-parses on every chunk. Replaces the previous "whole AssistantText
     * is a single LazyColumn item containing an internal Column of blocks"
     * design which caused the user's scroll position to drift mid-stream.
     */
    /**
     * See [AssistantText] for the rationale behind the hand-rolled equals.
     * `rawText` and `messageMarkdown` are both potentially long; we compare
     * by length (cheap proxy for "has content grown") and identity instead
     * of char-by-char.
     */
    class AssistantMarkdownBlock(
        val messageId: String,
        val parentBlockId: String,
        val rawText: String,
        val blockIndex: Int,
        val isLastBlockOfMessage: Boolean,
        val messageIsStreaming: Boolean,
        /** Joined raw markdown of the parent message, used by Copy Markdown. */
        val messageMarkdown: String,
        val showTranslate: Boolean = false,
        val segmentText: String = "",
        val translateWholeReply: Boolean = false,
    ) : FlatChatItem() {
        override val key = "mdblock:$messageId:$parentBlockId:$blockIndex"
        override val contentType = "mdblock"
        /** True when this fragment is the streaming tail of a live message. */
        val isStreaming: Boolean get() = messageIsStreaming && isLastBlockOfMessage
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantMarkdownBlock) return false
            return messageId == other.messageId &&
                parentBlockId == other.parentBlockId &&
                blockIndex == other.blockIndex &&
                isLastBlockOfMessage == other.isLastBlockOfMessage &&
                messageIsStreaming == other.messageIsStreaming &&
                rawText.length == other.rawText.length &&
                messageMarkdown.length == other.messageMarkdown.length &&
                showTranslate == other.showTranslate &&
                segmentText.length == other.segmentText.length &&
                translateWholeReply == other.translateWholeReply
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + parentBlockId.hashCode()
            h = h * 31 + blockIndex
            h = h * 31 + isLastBlockOfMessage.hashCode()
            h = h * 31 + messageIsStreaming.hashCode()
            h = h * 31 + rawText.length
            h = h * 31 + messageMarkdown.length
            h = h * 31 + if (showTranslate) 1 else 0
            h = h * 31 + segmentText.length
            h = h * 31 + if (translateWholeReply) 1 else 0
            return h
        }
    }

    data class AssistantThinking(
        val messageId: String,
        val block: AssistantBlock,
        val isLast: Boolean,
        val messageIsStreaming: Boolean,
        // T300: thinking level captured at the message's creation. Null
        // for assistant messages restored from DB (legacy / pre-T300) —
        // the renderer falls back to the chat's current level.
        val messageThinkingLevel: com.openminis.app.data.model.ThinkingLevel? = null,
        // [T-android-thinking-auto-collapse] True when this thinking block
        // is the LAST block of any kind in the message (including text /
        // tool_use), not merely the last thinking block. Drives the
        // auto-collapse `isStreaming` signal so a thinking block flips to
        // collapsed the moment a subsequent text or tool block arrives —
        // mirrors iOS ThinkingBlockView, which only sees `isStreaming=true`
        // while it really is the trailing block. Defaults false so DB-
        // restored / legacy items render collapsed (the pre-change
        // behaviour for non-trailing thinking).
        val isLastBlockOverall: Boolean = false,
    ) : FlatChatItem() {
        override val key = "thinking:$messageId:${block.id}"
        override val contentType = "thinking"
    }

    /** Collapsed thinking+tools header. Same decoration family as ThinkingBlock. */
    data class AssistantProcessSummary(
        val messageId: String,
        val thinkingCount: Int,
        val toolCount: Int,
        val expanded: Boolean,
        val hasFailure: Boolean,
        val processTools: List<ProcessToolRef> = emptyList(),
    ) : FlatChatItem() {
        override val key = "process:$messageId"
        override val contentType = "process"
    }

    data class AssistantToolUse(
        val messageId: String,
        val block: AssistantBlock,
        val allToolBlocks: List<AssistantBlock>,
        /** True if this is the last cancelled tool in its message — only one Retry button per message. */
        val isLastCancelled: Boolean = false,
    ) : FlatChatItem() {
        override val key = "tool:$messageId:${block.id}"
        override val contentType = "tool"
    }

    data class AssistantInfo(
        val messageId: String,
        val block: AssistantBlock,
    ) : FlatChatItem() {
        override val key = "info:$messageId:${block.id}"
        override val contentType = "info"
    }

    data class AssistantTyping(val messageId: String) : FlatChatItem() {
        override val key = "typing:$messageId"
        override val contentType = "typing"
    }

    data class AssistantError(val messageId: String, val error: String) : FlatChatItem() {
        override val key = "error:$messageId"
        override val contentType = "error"
    }

    /**
     * See [AssistantText] — same cheap-equals rationale.
     */
    class AssistantLegacyContent(
        val messageId: String,
        val content: String,
        val isStreaming: Boolean,
        /** Same as content here (no separate text-block markdown for legacy rows). */
        val messageMarkdown: String = content,
    ) : FlatChatItem() {
        override val key = "legacy:$messageId"
        override val contentType = "legacy"
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AssistantLegacyContent) return false
            return messageId == other.messageId &&
                isStreaming == other.isStreaming &&
                content.length == other.content.length &&
                messageMarkdown.length == other.messageMarkdown.length
        }
        override fun hashCode(): Int {
            var h = messageId.hashCode()
            h = h * 31 + isStreaming.hashCode()
            h = h * 31 + content.length
            h = h * 31 + messageMarkdown.length
            return h
        }
    }
}

/**
 * T-streaming-side-channel: overlay any active [StreamingDelta]s on top of
 * the canonical [messages] list, producing the snapshot
 * [buildFlatChatItems] should fold over. The original [messages] list is
 * never mutated; affected entries are replaced via `copy()` so downstream
 * keying / equality stays correct. When [streaming] is empty the input is
 * returned as-is to skip the per-element walk on idle frames.
 */
internal fun mergeStreamingOverlay(
    messages: List<ChatMessage>,
    streaming: Map<String, StreamingDelta>,
): List<ChatMessage> {
    if (streaming.isEmpty()) return messages
    return messages.map { m ->
        val delta = streaming[m.id] ?: return@map m
        m.copy(
            content = delta.content,
            isStreaming = true,
            toolBlocks = delta.toolBlocks,
            isAwaitingModelResponse = delta.isAwaitingModelResponse,
        )
    }
}

internal fun buildFlatChatItems(
    messages: List<ChatMessage>,
    // [T-android-perf-logging] Optional — when supplied, emit a progress
    // breadcrumb every 100 messages so a low-memory repro shows which batch
    // drives the heap up. Null (default) skips all progress logging, so the
    // hot per-token streaming rebuild path stays log-free.
    sessionId: String? = null,
    // [T-android-stream-pipeline-incremental] Build rows only for
    // messages[fromIndex, size). Neighbor lookbacks (precededByUser /
    // isResumeContinuation) still read the FULL list, so a suffix built with
    // fromIndex > 0 is row-for-row identical to the same span of a full
    // build — rows never depend on later messages, only earlier ones.
    fromIndex: Int = 0,
    // Dedupe continuity for split builds: pass the key set of the frozen
    // prefix so the defensive key-collision suffixing behaves exactly as a
    // single full build would.
    seedKeys: Set<String> = emptySet(),
    showCompletedToolCards: Boolean = true,
    foldAiProcess: Boolean = false,
    expandedProcessIds: Set<String> = emptySet(),
): List<FlatChatItem> {
    val out = mutableListOf<FlatChatItem>()
    val usedKeys = if (seedKeys.isEmpty()) mutableSetOf() else seedKeys.toMutableSet()
    fun dedupe(item: FlatChatItem): FlatChatItem {
        // Defensive: duplicated keys crash LazyColumn. If any slip through, suffix
        // a counter until unique. This should never fire if upstream dedup is correct.
        if (usedKeys.add(item.key)) return item
        var n = 2
        while (!usedKeys.add("${item.key}#$n")) n++
        return when (item) {
            is FlatChatItem.UserBubble -> FlatChatItem.UserBubble(item.message.copy(id = "${item.message.id}#$n"), item.precededByUser)
            is FlatChatItem.AssistantHeader -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantText -> FlatChatItem.AssistantText(
                messageId = "${item.messageId}#$n",
                block = item.block,
                isStreaming = item.isStreaming,
                messageMarkdown = item.messageMarkdown,
            )
            is FlatChatItem.AssistantMarkdownBlock -> FlatChatItem.AssistantMarkdownBlock(
                messageId = "${item.messageId}#$n",
                parentBlockId = item.parentBlockId,
                rawText = item.rawText,
                blockIndex = item.blockIndex,
                isLastBlockOfMessage = item.isLastBlockOfMessage,
                messageIsStreaming = item.messageIsStreaming,
                messageMarkdown = item.messageMarkdown,
                showTranslate = item.showTranslate,
                segmentText = item.segmentText,
                translateWholeReply = item.translateWholeReply,
            )
            is FlatChatItem.AssistantThinking -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantProcessSummary -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantToolUse -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantInfo -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantTyping -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantError -> item.copy(messageId = "${item.messageId}#$n")
            is FlatChatItem.AssistantLegacyContent -> FlatChatItem.AssistantLegacyContent(
                messageId = "${item.messageId}#$n",
                content = item.content,
                isStreaming = item.isStreaming,
                messageMarkdown = item.messageMarkdown,
            )
        }
    }
    for (idx in fromIndex until messages.size) {
        val message = messages[idx]
        // [T-android-perf-logging] Per-100-message progress breadcrumb.
        // `out.size` is the running row count, so a sudden jump between two
        // progress lines localizes the heavy batch. Only fires on the
        // full-build path (sessionId != null), never per streaming token.
        if (sessionId != null && idx > 0 && idx % 100 == 0) {
            com.openminis.app.diagnostics.PerfLongCtx.step(
                sessionId,
                "buildFlatChatItems.progress",
                "msgIdx=$idx of=${messages.size} rowsSoFar=${out.size}",
            )
        }
        if (message.role == "user") {
            // [T-android-candidate-bubble-gap] Flag when the previous message
            // is also a user message so the bubble can add a separating top
            // gap — back-to-back candidate / queued sends otherwise have no
            // AssistantHeader between them and visually merge.
            val prevIsUser = idx > 0 && messages[idx - 1].role == "user"
            out.add(dedupe(FlatChatItem.UserBubble(message, precededByUser = prevIsUser)))
            continue
        }
        // System messages (slash-command notices, compact divider, etc.) render
        // as horizontal-divider rows — no "Minis Ultra" attribution, no card. Skip
        // the assistant header so each info block stands on its own. Mirrors
        // iOS systemDividerRow / compactDividerRow.
        val isSystem = message.role == "system"
        val joinedMarkdown = run {
            val parts = message.toolBlocks
                .filter { it.kind == "text" && it.content.isNotEmpty() }
                .joinToString("\n\n") { it.content }
            if (parts.isNotEmpty()) parts else message.content
        }
        // T83: when Resume creates a fresh assistant bubble after the user
        // stopped a streaming turn, the previous (cancelled) assistant
        // message is right before this one in the list. Visually they should
        // read as one continuous turn — suppress the duplicate "Minis Ultra"
        // header. Skip system rows when looking back since they render as
        // dividers, not as separate speaker turns. iOS achieves this by
        // reusing the existing ChatMessage in runAgentLoop(resumingAt:);
        // we reach the same end-result at the render layer.
        val prevNonSystem = (idx - 1 downTo 0).asSequence()
            .map { messages[it] }
            .firstOrNull { it.role != "system" }
        val isResumeContinuation = prevNonSystem?.role == "assistant"
        if (!isSystem && !isResumeContinuation) {
            out.add(dedupe(FlatChatItem.AssistantHeader(message.id)))
        }

        val blocks = message.toolBlocks
        val toolPillBlocks = blocks.filter { it.kind == "tool_use" }
        val lastThinkingId = blocks.lastOrNull { it.kind == "thinking" }?.id
        // [T-android-thinking-auto-collapse] Id of the last block of ANY
        // kind — used to flip the trailing thinking block's auto-collapse
        // signal the moment a subsequent text / tool_use arrives. See
        // AssistantThinking.isLastBlockOverall KDoc.
        val lastBlockId = blocks.lastOrNull()?.id
        val lastTextIdx = blocks.indexOfLast { it.kind == "text" }
        val hasAnyTextBlock = lastTextIdx >= 0
        // Only the last cancelled tool_use in the message gets the Retry button —
        // retryLast() re-runs the whole turn, so one button is enough.
        val lastCancelledToolId = blocks.lastOrNull { it.kind == "tool_use" && it.toolStatus == ToolBlockStatus.CANCELLED }?.id
        val thinkingCount = blocks.count { it.kind == "thinking" }
        val toolCount = blocks.count { it.kind == "tool_use" }
        val processExpanded = message.id in expandedProcessIds
        // Fold completed thinking/tools as soon as they finish — even while
        // the turn is still live. Only the currently streaming thinking
        // block (last block overall) and in-flight tools stay expanded.
        // Waiting for the whole turn / tool-loop to end was the old gate.
        val liveThinkingId = liveThinkingBlockId(message.isStreaming, blocks)
        val hasFoldableProcess = blocks.any { block ->
            when (block.kind) {
                "thinking" -> block.id != liveThinkingId
                "tool_use" -> !isAlwaysVisibleProcessTool(block) &&
                    !isInFlightProcessTool(block)
                else -> false
            }
        }
        val showProcessSummary = foldAiProcess && !isSystem && hasFoldableProcess
        val replyText = AssistantReplyText.joined(blocks)
        blocks.forEachIndexed { index, block ->
            when (block.kind) {
                "text" -> {
                    if (block.content.isNotEmpty()) {
                        val isLastText = index == lastTextIdx
                        // Pattern A: split this text block's content into
                        // independent markdown fragments so each becomes its
                        // own LazyColumn item. Frozen prefix fragments are
                        // anchored separately by LazyList; only the trailing
                        // live fragment can change height during streaming.
                        //
                        // [T-android-defensive-fragment-merge] For a FROZEN
                        // (non-streaming) message, coalesce adjacent
                        // plain-text fragments so a long reply produces a
                        // handful of rows instead of dozens — cuts cold-open
                        // full-build row count ~8x and eases GC pressure on
                        // low-memory devices. The live streaming tail message
                        // keeps fine-grained fragments so only the trailing
                        // paragraph re-parses per token (Pattern A jank
                        // optimization preserved). Code fences stay standalone
                        // either way.
                        val rawFragments = splitMarkdownIntoBlockTexts(block.content)
                        // [T-android-stream-end-reflow-flicker-v18] Preserve
                        // per-fragment FlatChatItem keys across the
                        // streaming→idle boundary. Previously the trailing
                        // text block kept rawFragments only while
                        // `message.isStreaming==true`; the moment it flipped
                        // false the fragments coalesced into fewer rows, all
                        // mdblock:msgId:parentBlockId:N keys for N >= K
                        // suddenly vanished from the flatItems list. That
                        // wipe-and-rebuild was the "整个页面像被重刷" the
                        // user reported — LazyColumn lost every key it was
                        // using to anchor the viewport, fell back to numeric
                        // firstVisibleItemIndex, and parked the viewport on
                        // whatever row happened to take that numeric slot
                        // (often the previous assistant message).
                        //
                        // Fix: keep the live (== last in the list) text block
                        // on rawFragments regardless of isStreaming. The
                        // boundary that actually warrants coalesce is "a
                        // NEWER message exists below this one" — i.e. a
                        // subsequent user turn pushed this assistant turn
                        // into history. Until then, the same key set the
                        // user was scrolled into stays valid.
                        // [T-android-flatitems-sublist-cme] Index-based scan
                        // instead of messages.subList(idx+1, size).all{} — a
                        // subList is a live view sharing the parent's modCount,
                        // which threw ConcurrentModificationException when the
                        // backing list changed under it. A plain index loop
                        // touches no view.
                        val isLastAssistantTurn = idx == messages.lastIndex ||
                            (idx + 1 until messages.size).all { messages[it].role != "assistant" }
                        val fragments = if (isLastText && isLastAssistantTurn) {
                            rawFragments
                        } else {
                            coalesceMarkdownFragments(rawFragments)
                        }
                        if (fragments.isEmpty()) {
                            // Defensive: if the splitter returns nothing for
                            // a non-empty input (shouldn't happen), fall back
                            // to a single fragment so content isn't dropped.
                            out.add(dedupe(FlatChatItem.AssistantMarkdownBlock(
                                messageId = message.id,
                                parentBlockId = block.id,
                                rawText = block.content,
                                blockIndex = 0,
                                isLastBlockOfMessage = isLastText && message.isStreaming,
                                messageIsStreaming = message.isStreaming && isLastText,
                                messageMarkdown = joinedMarkdown,
                                showTranslate = !message.isStreaming && block.content.isNotBlank() &&
                                    (!showProcessSummary || isLastText),
                                segmentText = if (showProcessSummary && isLastText) replyText else block.content,
                                translateWholeReply = showProcessSummary && isLastText &&
                                    !message.isStreaming && block.content.isNotBlank(),
                            )))
                        } else {
                            fragments.forEachIndexed { fragIdx, raw ->
                                val isLastFragOfText = fragIdx == fragments.lastIndex
                                out.add(dedupe(FlatChatItem.AssistantMarkdownBlock(
                                    messageId = message.id,
                                    parentBlockId = block.id,
                                    rawText = raw,
                                    blockIndex = fragIdx,
                                    isLastBlockOfMessage = isLastText && isLastFragOfText,
                                    messageIsStreaming = message.isStreaming && isLastText,
                                    messageMarkdown = joinedMarkdown,
                                    showTranslate = isLastFragOfText && !message.isStreaming && block.content.isNotBlank() &&
                                        (!showProcessSummary || isLastText),
                                    segmentText = if (showProcessSummary && isLastText && isLastFragOfText) replyText
                                        else if (isLastFragOfText) block.content else "",
                                    translateWholeReply = showProcessSummary && isLastText && isLastFragOfText &&
                                        !message.isStreaming && block.content.isNotBlank(),
                                )))
                            }
                        }
                    }
                }
                "thinking" -> {
                    if (!showProcessSummary || processExpanded || block.id == liveThinkingId) {
                        out.add(dedupe(FlatChatItem.AssistantThinking(
                            messageId = message.id,
                            block = block,
                            isLast = block.id == lastThinkingId,
                            messageIsStreaming = message.isStreaming,
                            messageThinkingLevel = message.thinkingLevel,
                            isLastBlockOverall = block.id == lastBlockId,
                        )))
                    }
                }
                "info" -> out.add(dedupe(FlatChatItem.AssistantInfo(
                    messageId = message.id,
                    block = block,
                )))
                else -> if (shouldShowProcessToolRow(
                        block,
                        showCompletedToolCards = showCompletedToolCards,
                        showProcessSummary = showProcessSummary,
                        processExpanded = processExpanded,
                    )
                ) {
                    out.add(dedupe(FlatChatItem.AssistantToolUse(
                        messageId = message.id,
                        block = block,
                        allToolBlocks = toolPillBlocks,
                        isLastCancelled = block.id == lastCancelledToolId,
                    )))
                }
            }
        }

        // [T-android-fold-bar-order] The process summary (fold bar) is added
        // AFTER the content blocks, not before them. The chat LazyColumn is
        // `reverseLayout=true` — index 0 is the NEWEST item and rows render
        // bottom-up — so list order and visual order are INVERTED. Adding the
        // summary first put it at the visual TOP of the turn, above the reply
        // text; a long reply then scrolled it straight out of the viewport with
        // no way to reach the fold bar. Appending it here puts it visually
        // BELOW the reply, next to the content it summarises.
        if (showProcessSummary) {
            out.add(dedupe(FlatChatItem.AssistantProcessSummary(
                messageId = message.id,
                thinkingCount = thinkingCount,
                toolCount = toolCount,
                expanded = processExpanded,
                hasFailure = blocks.any {
                    it.kind == "tool_use" && it.toolStatus == ToolBlockStatus.FAILED
                },
                processTools = processToolRefs(blocks),
            )))
        }

        // Typing indicator: show while streaming and either (a) no visible
        // content has arrived yet, or (b) we're in the network gap waiting
        // on the model's next response (e.g. after tool results were sent
        // back). Mirrors iOS: `isActiveMessage && (!hasVisibleContent || isAwaitingModelResponse)`.
        //
        // [T-android-typing-hidden-thinking] "Visible" must mean WILL RENDER,
        // not merely "exists". Two blocks used to count as content while
        // drawing nothing, killing the indicator into a blank gap ("thinking
        // 还没等到内容出现就消失了"):
        //  - a "thinking" block when the message's thinking level is OFF —
        //    forced-reasoning models (MiniMax M2, Grok…) still stream
        //    reasoning_content, but ChatScreen suppresses the row when the
        //    snapshot level is disabled (T300), so the user saw nothing;
        //  - a freshly-created "text" block whose content is still empty.
        // A null thinkingLevel snapshot falls back to the chat's CURRENT
        // level in the renderer, which this pure builder can't read — treat
        // it as visible (legacy messages; conservative, old behavior).
        val hasVisibleContent = message.content.isNotEmpty() || blocks.any {
            when (it.kind) {
                "info" -> false
                "thinking" -> message.thinkingLevel?.isEnabled ?: true
                "text" -> it.content.isNotEmpty()
                else -> true // tool_use pills render immediately
            }
        }
        if (message.isStreaming && (!hasVisibleContent || message.isAwaitingModelResponse)) {
            out.add(dedupe(FlatChatItem.AssistantTyping(message.id)))
        }

        // Legacy fallback: pre-migration sessions stored all text in message.content
        // with no text-kind blocks. Render it after blocks in that case only.
        if (!hasAnyTextBlock && message.content.isNotEmpty()) {
            out.add(dedupe(FlatChatItem.AssistantLegacyContent(
                messageId = message.id,
                content = message.content,
                isStreaming = message.isStreaming,
            )))
        }

        // Inline error banner
        message.error?.let {
            out.add(dedupe(FlatChatItem.AssistantError(message.id, it)))
        }
    }
    return out
}

internal fun shouldShowToolUseRow(block: AssistantBlock, showCompletedToolCards: Boolean): Boolean {
    if (showCompletedToolCards) return true
    return when (block.toolStatus) {
        ToolBlockStatus.SUCCESS, ToolBlockStatus.FAILED, ToolBlockStatus.TIMEOUT -> false
        else -> true
    }
}

internal fun isAlwaysVisibleProcessTool(block: AssistantBlock): Boolean =
    block.kind == "tool_use" && block.toolName == "ask_user_question"

internal fun shouldShowProcessToolRow(
    block: AssistantBlock,
    showCompletedToolCards: Boolean,
    showProcessSummary: Boolean,
    processExpanded: Boolean,
): Boolean {
    if (isAlwaysVisibleProcessTool(block)) return true
    if (showProcessSummary) {
        // Expanded process lists thinking + tools in-thread. The fold bar no
        // longer carries tool chips, so hiding completed tools here would
        // make them unreachable.
        if (processExpanded) return true
        // Keep the in-progress tool visible; completed ones live in the summary.
        return isInFlightProcessTool(block)
    }
    return shouldShowToolUseRow(block, showCompletedToolCards)
}

private val IN_FLIGHT_PROCESS_TOOL_STATUSES = setOf(
    ToolBlockStatus.STREAMING,
    ToolBlockStatus.PENDING,
    ToolBlockStatus.RUNNING,
)

internal fun isInFlightProcessTool(block: AssistantBlock): Boolean =
    block.kind == "tool_use" && block.toolStatus in IN_FLIGHT_PROCESS_TOOL_STATUSES

internal fun liveThinkingBlockId(isStreaming: Boolean, blocks: List<AssistantBlock>): String? {
    if (!isStreaming) return null
    val last = blocks.lastOrNull() ?: return null
    return if (last.kind == "thinking") last.id else null
}

/** Compact identity for a folded process-summary chip. */
internal data class ProcessToolRef(
    val id: String,
    val title: String,
    val status: ToolBlockStatus?,
)

internal fun processToolRefs(blocks: List<AssistantBlock>): List<ProcessToolRef> =
    blocks.filter { it.kind == "tool_use" }.map { block ->
        ProcessToolRef(
            id = block.id,
            title = block.toolTitle.ifEmpty { block.toolName }.ifEmpty { "tool" },
            status = block.toolStatus,
        )
    }

/** Tool-use rows that belong in the detail sheet (completed or live). */
internal fun isDetailProcessTool(block: AssistantBlock): Boolean {
    if (block.toolStatus == null) return false
    if (block.kind == "thinking" || block.kind == "info") return false
    return true
}

internal fun assistantToolUseBlocks(messages: List<ChatMessage>): List<AssistantBlock> =
    messages.asSequence()
        .filter { it.role == "assistant" }
        .flatMap { it.toolBlocks.asSequence() }
        .filter(::isDetailProcessTool)
        .toList()

/**
 * Whether [block] belongs on the floating tool overlay. When
 * [foldAiProcess] is on, completed tools fold into the in-list summary
 * and must not linger as a second "computer" strip — that was why the
 * Appearance switch looked like a no-op.
 *
 * The overlay subset is *not* the source of truth for ToolDetailSheet:
 * completed tools must remain openable after they leave the overlay.
 */
internal fun isFloatingProcessTool(block: AssistantBlock, foldAiProcess: Boolean): Boolean {
    if (!isDetailProcessTool(block)) return false
    if (foldAiProcess && block.toolStatus !in IN_FLIGHT_PROCESS_TOOL_STATUSES) return false
    return true
}
